[package]
name = "wasmtime-functions"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[dependencies]
wasmtime-functions-codegen = { path = "../codegen" }
http = "0.2.1"
time = "0.2.16"
