[package]
name = "wasmtime-functions-runtime"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[dependencies]
wasmtime-functions-metadata = { path = "../metadata" }
wiggle = "0.19.0"
wasmtime-wiggle = "0.19.0"
tide = "0.13.0"
http-types = "2.4.0"
time = "0.2.16"
anyhow = "1.0.32"
bytes = "0.5.6"
async-std = "1.6.3"
async-h1 = "2.1.2"
async-trait = "0.1.38"
log = "0.4.11"
stop-token = "0.1.2"
wasmtime = "0.19.0"
wasmtime-wasi = "0.19.1"
futures-timer = "3.0.2"
futures = "0.3.5"
