[package]
name = "hello-example"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmtime-functions = { path = "../../crates/functions" }
