[package]
name = "wasmtime-functions-metadata"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[dependencies]
anyhow = "1.0.42"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
wasmparser = "0.79.0"
